export const MILLIS_WEEK = 7 * 24 * 3600 * 1000;

export const RENEW_PERIOD_WEEKS = 2;
export const RENEW_PERIOD_MILLIS = RENEW_PERIOD_WEEKS * MILLIS_WEEK;
export const EXPIRE_PERIOD_WEEKS = 8;
export const EXPIRE_PERIOD_MILLIS = EXPIRE_PERIOD_WEEKS * MILLIS_WEEK;
